API_HOST_URL: 'http://courses.mutalashi.com'
ENVIRONMENT_DISPLAY_NAME: ''
PLATFORM_NAME: 'Mutalashi'
PLATFORM_DESTINATION_NAME: 'example.com'
FEEDBACK_EMAIL_ADDRESS: 'support@example.com'

COURSE_ENROLLMENT:
    TYPE: 'native'

USER_PROFILES_ENABLED: true
ANNOUNCEMENTS_ENABLED: true
DISCUSSIONS_ENABLED: true
DISCUSSIONS_ENABLE_PROFILE_PICTURE_PARAM: true
BADGES_ENABLED: false
CERTIFICATES_ENABLED: true
COURSE_SHARING_ENABLED: true
COURSE_VIDEOS_ENABLED: true
REGISTRATION_ENABLED: true
TABS_DASHBOARD_ENABLED: true
VIDEO_TRANSCRIPT_ENABLED: true
TAB_LAYOUTS_ENABLED: true

FACEBOOK:
    ENABLED: true
    FACEBOOK_APP_ID: '1463337977100619'

GOOGLE:
    ENABLED: true
    GOOGLE_PLUS_KEY: '671521085289-qvevkrglqjlisirnrrafgaq9smlciaef.apps.googleusercontent.com'
