API_HOST_URL: 'https://courses.matriconline.com'
ENVIRONMENT_DISPLAY_NAME: ''
PLATFORM_NAME: 'Matric Online'
PLATFORM_DESTINATION_NAME: 'matriconline.com'
FEEDBACK_EMAIL_ADDRESS: 'support@example.com'

COURSE_ENROLLMENT:
    TYPE: 'native'

USER_PROFILES_ENABLED: true
ANNOUNCEMENTS_ENABLED: true
DISCUSSIONS_ENABLED: true
DISCUSSIONS_ENABLE_PROFILE_PICTURE_PARAM: true
BADGES_ENABLED: false
CERTIFICATES_ENABLED: true
COURSE_SHARING_ENABLED: true
COURSE_VIDEOS_ENABLED: true
REGISTRATION_ENABLED: true
TABS_DASHBOARD_ENABLED: true
VIDEO_TRANSCRIPT_ENABLED: true
TAB_LAYOUTS_ENABLED: true

FACEBOOK:
    ENABLED: true
    FACEBOOK_APP_ID: '270420543554058'

GOOGLE:
    ENABLED: true
    GOOGLE_PLUS_KEY: '685570419285-b589cj0vhq2e8sgektps8u81aaidh597.apps.googleusercontent.com'
