API_HOST_URL: 'https://courses.tsbeducation.com'
ENVIRONMENT_DISPLAY_NAME: ''
PLATFORM_NAME: 'TSB Education'
PLATFORM_DESTINATION_NAME: 'tsbeducation.com'
FEEDBACK_EMAIL_ADDRESS: 'support@example.com'

COURSE_ENROLLMENT:
    TYPE: 'native'

USER_PROFILES_ENABLED: true
ANNOUNCEMENTS_ENABLED: true
DISCUSSIONS_ENABLED: true
DISCUSSIONS_ENABLE_PROFILE_PICTURE_PARAM: true
BADGES_ENABLED: false
CERTIFICATES_ENABLED: true
COURSE_SHARING_ENABLED: true
COURSE_VIDEOS_ENABLED: true
REGISTRATION_ENABLED: true
TABS_DASHBOARD_ENABLED: true
VIDEO_TRANSCRIPT_ENABLED: true
TAB_LAYOUTS_ENABLED: true

FACEBOOK:
    ENABLED: true
    FACEBOOK_APP_ID: '228183481220645'

GOOGLE:
    ENABLED: true
    GOOGLE_PLUS_KEY: '992313764382-b6gr8orjbstbtuip11ki6pb73i9ao3qu.apps.googleusercontent.com'
